// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwstpeM4MkOs9aNkh9faJQm-1jggbMZZE',
    appId: '1:848662087857:web:0c1349bc37248181a0fa90',
    messagingSenderId: '848662087857',
    projectId: 'resturant-e0389',
    authDomain: 'resturant-e0389.firebaseapp.com',
    storageBucket: 'resturant-e0389.firebasestorage.app',
    measurementId: 'G-3ZP3CLYH3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCeq10TVDQieXf6yw_A7fSekVec-mu5BM',
    appId: '1:848662087857:android:1929a61f23f6da50a0fa90',
    messagingSenderId: '848662087857',
    projectId: 'resturant-e0389',
    storageBucket: 'resturant-e0389.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC39nk0Hv_0cHy1nDeHmoAbTESUaY8OIKw',
    appId: '1:848662087857:ios:6d9695af18aab7f9a0fa90',
    messagingSenderId: '848662087857',
    projectId: 'resturant-e0389',
    storageBucket: 'resturant-e0389.firebasestorage.app',
    androidClientId: '848662087857-li2g9jfhq7nejns3gmk2of6q7lp11jga.apps.googleusercontent.com',
    iosClientId: '848662087857-6vv6v0k6286amfnlg8t3ct5135ckiil1.apps.googleusercontent.com',
    iosBundleId: 'com.example.animation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC39nk0Hv_0cHy1nDeHmoAbTESUaY8OIKw',
    appId: '1:848662087857:ios:6d9695af18aab7f9a0fa90',
    messagingSenderId: '848662087857',
    projectId: 'resturant-e0389',
    storageBucket: 'resturant-e0389.firebasestorage.app',
    androidClientId: '848662087857-li2g9jfhq7nejns3gmk2of6q7lp11jga.apps.googleusercontent.com',
    iosClientId: '848662087857-6vv6v0k6286amfnlg8t3ct5135ckiil1.apps.googleusercontent.com',
    iosBundleId: 'com.example.animation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwstpeM4MkOs9aNkh9faJQm-1jggbMZZE',
    appId: '1:848662087857:web:6a9440ed17bbd204a0fa90',
    messagingSenderId: '848662087857',
    projectId: 'resturant-e0389',
    authDomain: 'resturant-e0389.firebaseapp.com',
    storageBucket: 'resturant-e0389.firebasestorage.app',
    measurementId: 'G-JJBP71EHH6',
  );

}